module.exports = {
    menuItemsData:[
        {
            id:1,
            type:'side',
            name:'fries',
            ingredients:'',
            price:100
        },
        {
            id:2,
            type:'side',
            name:'burger',
            ingredients:'',
            price:350
        },
        {
            id:3,
            type:'side',
            name:'onion rings',
            ingredients:'10 pieces',
            price:200
        },
        {
            id:4,
            type:'drink',
            name:'Fanta',
            ingredients:'500ml',
            price:100
        },
        {
            id:5,
            type:'meal',
            name:'Super Combo',
            ingredients:'2 fries, 6 wings, 1 burger and one 2 liter Soda',
            price:1200
        }
    ],
    orders:[
            {
                number:21,
                id:1,
                user:'edwin',
                status:0
            },
            {
                number:23,
                id:2,
                user:'abbie',
                status:1
            },
            {
                number:24,
                id:3,
                user:'john',
                status:2
            },
            {
                number:25,
                id:4,
                user:'patrick',
                status:3
            },
            {
                number:26,
                id:5,
                user:'natalya',
                status:4
            }
    ]   
}